import{SVG_NS,seededRandom,pick,roughPath,roughEllipse,svgPath}from'../../src/drawing-engine.js';
const INK='#292b29',BLUE='#596f79',RUST='#956149',GROUND=205;
export const VIEWS=['side','front','rear','three-quarter front','three-quarter rear'];
export const FAMILIES=['walking','cycling','motorcycle','three-wheeler','car','public transport','freight','agricultural','accessible mobility','cart'];
export const DIMENSIONS={
 pedestrian:{length:.45,width:.5,height:1.72,wheelbase:0,wheelRadius:0},porter:{length:.55,width:.6,height:1.7,wheelbase:0,wheelRadius:0},wheelchair:{length:1.05,width:.68,height:1.25,wheelbase:.62,wheelRadius:.31},
 bicycle:{length:1.75,width:.55,height:1.08,wheelbase:1.08,wheelRadius:.34},motorcycle:{length:2.05,width:.78,height:1.18,wheelbase:1.39,wheelRadius:.3},scooter:{length:1.82,width:.68,height:1.14,wheelbase:1.27,wheelRadius:.235},
 threeWheeler:{length:2.8,width:1.35,height:1.72,wheelbase:1.9,wheelRadius:.28},car:{length:4.15,width:1.72,height:1.5,wheelbase:2.55,wheelRadius:.31},jeep:{length:4.25,width:1.82,height:1.78,wheelbase:2.55,wheelRadius:.36},
 pickup:{length:4.9,width:1.82,height:1.78,wheelbase:2.95,wheelRadius:.36},microbus:{length:5.35,width:1.9,height:2.35,wheelbase:3.15,wheelRadius:.36},bus:{length:9.2,width:2.45,height:3.2,wheelbase:5.4,wheelRadius:.49},
 truck:{length:7.1,width:2.35,height:3.05,wheelbase:4.2,wheelRadius:.48},tractor:{length:3.45,width:1.8,height:2.25,wheelbase:2.05,wheelRadius:.6,frontWheelRadius:.34},cart:{length:2.15,width:1.05,height:1.35,wheelbase:1.3,wheelRadius:.31}
};
const variants={
 walking:['pedestrian','porter','person carrying load','person with umbrella'],cycling:['road bicycle','utility bicycle','bicycle with rear carrier','bicycle carrying goods','school bicycle','older roadster bicycle'],motorcycle:['commuter motorcycle','utility motorcycle','sport motorcycle','older motorcycle','motorcycle with passenger','scooter'],
 'three-wheeler':['electric tempo','passenger tempo','goods three-wheeler'],car:['small hatchback','compact sedan','small SUV','jeep-like utility vehicle','taxi','older compact car'],
 'public transport':['microbus','high-roof microbus','local bus','large bus','school bus'],freight:['small pickup','double-cab pickup','loaded pickup','mini truck','cargo truck','tipper truck'],agricultural:['tractor','tractor with trailer','rural utility tractor'],cart:['two-wheel handcart','vendor cart','flat goods cart','wheelbarrow'],
 'accessible mobility':['wheelchair user','person with walking stick']
};
const typeFor=(family,label)=>family==='walking'?(label.includes('porter')||label.includes('load')?'porter':'pedestrian'):family==='cycling'?'bicycle':family==='motorcycle'?(label==='scooter'?'scooter':'motorcycle'):family==='three-wheeler'?'threeWheeler':family==='car'?(label.includes('SUV')||label.includes('jeep')?'jeep':'car'):family==='public transport'?(label.includes('microbus')?'microbus':'bus'):family==='freight'?(label.includes('pickup')?'pickup':'truck'):family==='agricultural'?'tractor':family==='accessible mobility'?'wheelchair':'cart';
export function mobility(seed,index=0,forced={}){const r=seededRandom(seed),family=forced.family||FAMILIES[index%FAMILIES.length],label=forced.type||pick(r,variants[family]),type=typeFor(family,label),base=DIMENSIONS[type],dimensions={...base};for(const k of ['length','width','height','wheelbase','wheelRadius'])if(dimensions[k])dimensions[k]*=.97+r()*.06;const view=forced.view||pick(r,VIEWS),lod=forced.lod??3;const rearAxle=-dimensions.wheelbase/2,frontAxle=dimensions.wheelbase/2;return{id:`MOVE-${String(index+1).padStart(3,'0')}`,seed,family,group:family==='cycling'?'cycles':family==='motorcycle'?'two-wheelers':family==='three-wheeler'||type==='microbus'?'small-public':['car'].includes(family)?'road-vehicles':['public transport','freight','agricultural'].includes(family)?'heavy':family==='walking'||family==='accessible mobility'?'walking':'service',type:label,geometryType:type,context:forced.context||pick(r,['urban','peri-urban','bazaar','rural','mountain','Terai']),view,lod,dimensions,axles:type==='threeWheeler'?[{x:frontAxle,count:1,role:'front'},{x:rearAxle,count:2,role:'rear'}]:dimensions.wheelRadius?[{x:rearAxle,count:1,role:'rear'},{x:frontAxle,count:1,role:'front'}]:[],footprint:{length:dimensions.length,width:dimensions.width},heading:forced.heading??0,movement:forced.movement||pick(r,['parked','standing','movingSlow','moving','loading','waiting']),passengers:forced.passengers||pick(r,['empty/parked','driver only','driver + passenger','multiple passengers']),cargo:forced.cargo||pick(r,['none','none','light load','moderate load']),weights:{urban:.2+r()*.8,semiUrban:.3+r()*.7,rural:.2+r()*.8,hill:.2+r()*.8,Terai:.2+r()*.8}}
}
const P=(pts,r,a='',close=false,j=.55)=>svgPath(roughPath(pts,r,{close,jitter:j}),a,{fill:'none',stroke:INK});
function wheel(cx,cy,rad,r,{view='side',lod=2,near=true,debug=false}={}){const ratio=view==='side'?1:view.includes('three')?(near?.62:.48):.24,rx=rad*ratio;let s=roughEllipse(cx,cy,rx,rad,r,{points:32,noise:.012,jitter:.28});s=`<path d="${s}" fill="none" stroke="${INK}" stroke-width="1.5"/>`;if(lod>0)s+=`<ellipse cx="${cx}" cy="${cy}" rx="${Math.max(1,rx*.18)}" ry="${Math.max(1,rad*.18)}" fill="none" stroke="${INK}" stroke-width=".8"/>`;if(lod>1&&ratio>.35)for(let i=0;i<(lod>2?8:4);i++){const a=Math.PI*2*i/(lod>2?8:4);s+=`<line x1="${cx}" y1="${cy}" x2="${cx+Math.cos(a)*rx*.82}" y2="${cy+Math.sin(a)*rad*.82}" stroke="${INK}" stroke-width=".45"/>`}if(debug)s+=`<circle cx="${cx}" cy="${cy}" r="2.5" fill="#b44"/>`;return s}
function person(d,r,S,cx){const h=d.dimensions.height*S,head=h/15,y=GROUND-h,walking=d.movement.includes('moving'),hip=[cx,GROUND-h*.46],shoulder=[cx,GROUND-h*.73];let s=roughEllipse(cx,y+head,head,head*1.08,r,{points:20,noise:.02,jitter:.35});s=`<path d="${s}" fill="none" stroke="${INK}" stroke-width="1.2"/>`+P([[cx,y+head*2],[shoulder[0],shoulder[1]],[hip[0],hip[1]]],r,'stroke-width="1.25"');s+=P([shoulder,[cx-h*.15,GROUND-h*.48]],r,'stroke-width="1"')+P([shoulder,[cx+h*.14,GROUND-h*.5]],r,'stroke-width="1"')+P([hip,[cx-h*(walking?.12:.07),GROUND]],r,'stroke-width="1.2"')+P([hip,[cx+h*(walking?.15:.07),GROUND]],r,'stroke-width="1.2"');if(d.type.includes('porter')||d.type.includes('load'))s+=P([[cx-h*.16,GROUND-h*.75],[cx-h*.35,GROUND-h*.7],[cx-h*.29,GROUND-h*.38],[cx-h*.13,GROUND-h*.45]],r,'fill="#956149" fill-opacity=".08" stroke-width="1"',true);if(d.type.includes('umbrella'))s+=P([[cx-h*.18,GROUND-h*.86],[cx,GROUND-h],[cx+h*.22,GROUND-h*.86]],r,'stroke-width="1.1"');return s}
function bicycle(d,r,S,cx){const m=d.dimensions,rad=m.wheelRadius*S,wb=m.wheelbase*S,rear=cx-wb/2,front=cx+wb/2,y=GROUND-rad,bb=[cx,GROUND-rad*.95],seat=[cx-wb*.16,GROUND-rad*2.15],head=[cx+wb*.25,GROUND-rad*2.12];let s=wheel(rear,y,rad,r,{view:d.view,lod:d.lod})+wheel(front,y,rad,r,{view:d.view,lod:d.lod});s+=P([[rear,y],bb,seat,[rear,y],[head[0],head[1]],bb,[front,y],head],r,'stroke-width="1.25"')+P([[seat[0]-rad*.25,seat[1]],[seat[0]+rad*.25,seat[1]]],r,'stroke-width="1.6"')+P([[head[0],head[1]],[head[0]+rad*.18,head[1]-rad*.38]],r,'stroke-width="1"');if(d.type.includes('carrier')||d.cargo!=='none')s+=P([[rear-rad*.7,y-rad*.85],[rear+rad*.4,y-rad*.85]],r,'stroke-width="1.1"');return s}
function motorcycle(d,r,S,cx){const m=d.dimensions,rad=m.wheelRadius*S,wb=m.wheelbase*S,rear=cx-wb/2,front=cx+wb/2,y=GROUND-rad;if(d.geometryType==='scooter'){let s=wheel(rear,y,rad,r,{view:d.view,lod:d.lod})+wheel(front,y,rad,r,{view:d.view,lod:d.lod});return s+P([[rear,y-rad*.7],[cx-rad*.35,y-rad*1.25],[cx+rad*.1,y-rad*.6],[front-rad*.3,y-rad*.75],[front-rad*.18,y-rad*2.35],[front+rad*.08,y-rad*2.8]],r,'fill="#596f79" fill-opacity=".06" stroke-width="1.5"')+P([[rear-rad*.1,y-rad*1.85],[cx+rad*.3,y-rad*1.85]],r,'stroke-width="2"')}
 let s=wheel(rear,y,rad,r,{view:d.view,lod:d.lod})+wheel(front,y,rad,r,{view:d.view,lod:d.lod});s+=P([[rear,y],[cx-rad*.2,y-rad*1.15],[front,y],[cx+rad*.15,y-rad*1.9],[rear+rad*.3,y-rad*1.8],[rear,y]],r,'stroke-width="1.35"')+P([[front,y],[front-rad*.15,y-rad*2.45],[front+rad*.18,y-rad*2.75]],r,'stroke-width="1.2"')+P([[rear+rad*.15,y-rad*2.05],[cx+rad*.45,y-rad*2.05]],r,'stroke-width="2"');return s}
function bodyVehicle(d,r,S,cx){const m=d.dimensions,L=m.length*S,H=m.height*S,rad=m.wheelRadius*S,rear=cx-m.wheelbase*S/2,front=cx+m.wheelbase*S/2,y=GROUND-rad,kind=d.geometryType,base=GROUND-rad*.72,left=cx-L/2,right=cx+L/2;let wheels='';const rearRad=kind==='tractor'?m.wheelRadius*S:rad,frontRad=kind==='tractor'?(m.frontWheelRadius||.34)*S:rad;wheels+=wheel(rear,GROUND-rearRad,rearRad,r,{view:d.view,lod:d.lod,near:true,debug:false})+wheel(front,GROUND-frontRad,frontRad,r,{view:d.view,lod:d.lod,near:true,debug:false});let outline=[];
 if(kind==='car'||kind==='jeep')outline=[[left,base],[left+L*.08,base-H*.25],[left+L*.24,base-H*.34],[left+L*.36,base-H*.7],[left+L*.7,base-H*.7],[left+L*.86,base-H*.34],[right,base-H*.22],[right,base],[front+rad*.9,base],[front+rad*.72,base-rad*.72],[front-rad*.72,base-rad*.72],[front-rad*.9,base],[rear+rad*.9,base],[rear+rad*.72,base-rad*.72],[rear-rad*.72,base-rad*.72],[rear-rad*.9,base]];
 else if(kind==='pickup')outline=[[left,base],[left+L*.05,base-H*.35],[left+L*.18,base-H*.45],[left+L*.28,base-H*.76],[left+L*.52,base-H*.76],[left+L*.62,base-H*.42],[right,base-H*.42],[right,base],[front+rad,base],[front+rad*.72,base-rad*.72],[front-rad*.72,base-rad*.72],[front-rad,base],[rear+rad,base],[rear+rad*.72,base-rad*.72],[rear-rad*.72,base-rad*.72],[rear-rad,base]];
 else if(kind==='threeWheeler')outline=[[left,base],[left+L*.04,base-H*.45],[left+L*.2,base-H*.7],[left+L*.38,base-H*.9],[right-L*.06,base-H*.9],[right,base-H*.68],[right,base],[front+rad*.9,base],[front+rad*.7,base-rad*.72],[front-rad*.7,base-rad*.72],[front-rad*.9,base],[rear+rad*.9,base],[rear+rad*.7,base-rad*.72],[rear-rad*.7,base-rad*.72],[rear-rad*.9,base]];
 else if(kind==='cart')outline=[[left,base-H*.18],[left+L*.12,base-H*.62],[right-L*.08,base-H*.62],[right,base-H*.18],[right-L*.08,base],[left+L*.08,base]];
 else if(kind==='tractor')outline=[[left,base],[left+L*.08,base-H*.4],[left+L*.38,base-H*.44],[left+L*.48,base-H*.82],[left+L*.65,base-H*.82],[left+L*.72,base-H*.45],[right,base-H*.38],[right,base],[front+frontRad,base],[front+frontRad*.8,base-frontRad],[front-frontRad*.8,base-frontRad],[front-frontRad,base],[rear+rearRad,base],[rear+rearRad*.8,base-rearRad],[rear-rearRad*.8,base-rearRad],[rear-rearRad,base]];
 else{const roof=kind==='bus'?H*.93:kind==='truck'?H*.77:H*.86;outline=[[left,base],[left,base-roof],[right-L*.04,base-roof],[right,base-H*.7],[right,base],[front+rad,base],[front+rad*.72,base-rad*.72],[front-rad*.72,base-rad*.72],[front-rad,base],[rear+rad,base],[rear+rad*.72,base-rad*.72],[rear-rad*.72,base-rad*.72],[rear-rad,base]]}
 let s=P(outline,r,'fill="#596f79" fill-opacity=".035" stroke-width="1.5"',true)+wheels;
 if(d.lod>1){if(['bus','microbus'].includes(kind)){const n=kind==='bus'?7:4;for(let i=0;i<n;i++){const x=left+L*(.08+i*.82/n),w=L*.62/n;s+=P([[x,base-H*.78],[x+w,base-H*.78],[x+w,base-H*.48],[x,base-H*.48]],r,'stroke-width=".65"',true)}}else if(kind==='truck')s+=P([[left+L*.42,base-H*.68],[right-L*.05,base-H*.68]],r,'stroke-width=".8"');else s+=P([[left+L*.32,base-H*.62],[left+L*.68,base-H*.62],[left+L*.78,base-H*.38],[left+L*.23,base-H*.38]],r,'stroke-width=".75"',true)}
 if(d.type.includes('taxi'))s+=P([[cx-L*.08,base-H*.75],[cx+L*.08,base-H*.75]],r,'stroke-width="2"');return s
}
function frontVehicle(d,r,S,cx){const m=d.dimensions,W=m.width*S,H=m.height*S,rad=m.wheelRadius*S||.2*S,left=cx-W/2,right=cx+W/2,top=GROUND-H;let s=P([[left,GROUND-rad*.2],[left,top+H*.24],[left+W*.16,top],[right-W*.16,top],[right,top+H*.24],[right,GROUND-rad*.2]],r,'stroke-width="1.55"',true);if(d.geometryType==='threeWheeler')s+=wheel(cx,GROUND-rad,rad,r,{view:'front',lod:d.lod});else s+=wheel(left+rad*.45,GROUND-rad,rad,r,{view:'front',lod:d.lod})+wheel(right-rad*.45,GROUND-rad,rad,r,{view:'front',lod:d.lod});if(d.lod>0)s+=P([[left+W*.14,top+H*.2],[right-W*.14,top+H*.2],[right-W*.22,top+H*.55],[left+W*.22,top+H*.55]],r,'stroke-width=".8"',true);if(d.geometryType==='threeWheeler')s+=P([[cx,GROUND-rad*2],[cx,top+H*.54]],r,'stroke-width=".65"');return s}
function renderDebug(d,S,cx){const m=d.dimensions,L=m.length*S,H=m.height*S;let s=`<rect x="${cx-L/2}" y="${GROUND-H}" width="${L}" height="${H}" fill="none" stroke="#b44" stroke-width=".7" stroke-dasharray="4 3"/>`;for(const a of d.axles)s+=`<line x1="${cx+a.x*S}" y1="${GROUND}" x2="${cx+a.x*S}" y2="${GROUND-H}" stroke="#b44" stroke-width=".6"/><circle cx="${cx+a.x*S}" cy="${GROUND}" r="2" fill="#b44"/>`;return s+`<line x1="20" y1="${GROUND}" x2="340" y2="${GROUND}" stroke="#b44" stroke-width=".6"/>`}
export function validateMobility(d){const m=d.dimensions,issues=[];if(m.wheelbase&&m.wheelbase>=m.length)issues.push('wheelbase exceeds length');if(m.wheelRadius&&m.wheelRadius*2>m.height*.8)issues.push('wheel too large');if(d.geometryType==='bicycle'&&Math.abs(d.axles[0].x+d.axles[1].x)>.01)issues.push('bicycle axle mismatch');if(d.geometryType==='threeWheeler'&&d.axles.map(a=>a.count).join(',')!=='1,2')issues.push('three-wheel architecture invalid');return{passed:!issues.length,issues}}
export function renderMobility(d,{paper=false,label=false,debug=false,trueScale=false,lod=d.lod}={}){const r=seededRandom(d.seed+'draw'),m=d.dimensions,max=Math.max(m.length||1,m.height||1.7),S=trueScale?28:Math.min(88,250/max),cx=180,dd={...d,lod};let marks;if(['pedestrian','porter','wheelchair'].includes(d.geometryType))marks=person(dd,r,S,cx);else if(d.geometryType==='bicycle')marks=bicycle(dd,r,S,cx);else if(['motorcycle','scooter'].includes(d.geometryType))marks=motorcycle(dd,r,S,cx);else if(d.view==='front'||d.view==='rear')marks=frontVehicle(dd,r,S,cx);else marks=bodyVehicle(dd,r,S,cx);if(debug)marks+=renderDebug(dd,S,cx);return`<svg xmlns="${SVG_NS}" viewBox="0 0 360 250"><rect width="100%" height="100%" fill="${paper?'#eee9dc':'transparent'}"/><g id="mobility">${marks}<path d="M 28 ${GROUND+.5} L 332 ${GROUND+.5}" fill="none" stroke="${INK}" stroke-width=".55" stroke-opacity=".45"/></g>${label?`<text x="8" y="240" font-size="7" font-family="monospace" fill="${INK}">${d.id} · ${d.type} · ${d.view}</text>`:''}</svg>`}
export function prototypePopulation(){const counts=[['walking',4],['cycling',4],['motorcycle',4],['three-wheeler',4],['car',6],['public transport',6],['freight',6],['agricultural',4],['cart',4]],out=[];for(const[f,n]of counts)for(let i=0;i<n;i++)out.push(mobility(`mobility-prototype-${f}-${i}`,out.length,{family:f,view:i%3===1?'three-quarter front':'side'}));return out}
export function population(offset=0){return Array.from({length:120},(_,i)=>mobility(`mobility-nepal-${offset}-${i}`,i))}
export function posterSVG(list,{cols=6,trueScale=false,debug=false}={}){const cw=360,ch=250,rows=Math.ceil(list.length/cols);return`<svg xmlns="${SVG_NS}" viewBox="0 0 ${cols*cw} ${rows*ch}"><rect width="100%" height="100%" fill="#eee9dc"/>${list.map((d,i)=>`<g transform="translate(${i%cols*cw} ${Math.floor(i/cols)*ch})">${renderMobility(d,{label:true,trueScale,debug}).replace(/^<svg[^>]*>|<\/svg>$/g,'')}</g>`).join('')}</svg>`}
