import{SVG_NS,seededRandom,pick,chance,roughPath,svgPath,downloadText,downloadSvgAsPng}from'../../src/drawing-engine.js';
const inert={insertAdjacentHTML(){},classList:{add(){},remove(){},toggle(){}},showModal(){},close(){},value:'all',selectedOptions:[{textContent:''}],style:{}};
const $=s=>(typeof document!=='undefined'&&document.querySelector(s))||inert,INK='#292a28';
const CONTEXTS=['urban','semiUrban','rural'],GEOGRAPHIES=['mountain','highHill','midHill','innerValley','Terai'];
const USES=['residential','mixed residential-commercial','commercial','institutional','educational','health','community','agricultural','workshop','storage','hospitality'];
const CONSTRUCTIONS=['RCC frame + masonry infill','brick masonry','stone masonry + mud mortar','timber-masonry hybrid','earthen construction','confined masonry','corrugated lightweight','mixed incremental'];
const URBAN=['ordinary RCC house','narrow plot house','mixed-use shop-house','incremental RCC','Newar-inspired residence','traditional-modern hybrid','row building','apartment','modest institution'];
const SEMI=['roadside RCC house','roadside shop-house','old + new hybrid','RCC + corrugated roof','workshop','warehouse / godown','small lodge','construction in progress'];
const RURAL=['stone hill house','slate-roof house','mud-plastered house','brick rural house','timber-masonry house','Terai verandah house','reconstruction house','agricultural structure','animal or storage shed','rural hybrid'];
const ROOFS=['flat parapet','flat unfinished','flat + rooftop room','simple gable','wide gable','steep slate','corrugated pitched','tile pitched','hipped','thatch','hybrid flat-pitched'];
const MASSINGS=['simple rectangle','long rectangle','tall narrow block','stepped volume','two connected blocks','side extension','stacked incremental','asymmetric upper story','roof-level room','courtyard edge'];
const FINISHES=['plaster','rough plaster','exposed brick','stone','unfinished masonry','mixed finishes','earth plaster'],WINDOWS=['small timber','double timber','modern rectangular','sliding','steel frame','grilled','traditional rhythm','shopfront'];
const BALCONIES=['none','small concrete','continuous concrete','deep verandah','timber balcony','metal railing','enclosed later','partial verandah'];
const STATES=['complete','unfinished facade','unfinished upper floor','under vertical extension','exposed masonry','temporary enclosure'],AGES=['new','recent','mature','old','very old'],MAINT=['well maintained','ordinary','weathered','under renovation','under construction'];
const additions=['none','upper floor addition','side extension','balcony enclosure','roof room','metal awning','corrugated lean-to','exterior stair','water tank','solar panel','patched facade'];
const weighted=(r,values,weights)=>{let n=r()*weights.reduce((a,b)=>a+b,0);for(let i=0;i<values.length;i++){n-=weights[i];if(n<=0)return values[i]}return values.at(-1)};
function building(seed,index=0,forced={}){const r=seededRandom(seed),context=forced.context||CONTEXTS[Math.floor(index/80)%3],families=context==='urban'?URBAN:context==='semiUrban'?SEMI:RURAL,family=forced.family||pick(r,families);let geography=context==='rural'?weighted(r,GEOGRAPHIES,[12,18,35,12,23]):weighted(r,GEOGRAPHIES,[2,5,38,27,28]);let construction=context==='urban'?weighted(r,CONSTRUCTIONS,[52,20,1,3,1,8,3,12]):context==='semiUrban'?weighted(r,CONSTRUCTIONS,[35,20,8,5,5,8,8,11]):weighted(r,CONSTRUCTIONS,[8,16,30,12,15,10,5,4]);if(family.includes('stone')||family.includes('slate'))construction='stone masonry + mud mortar';if(family.includes('mud'))construction='earthen construction';if(family.includes('timber'))construction='timber-masonry hybrid';if(family.includes('RCC')||family.includes('apartment')||family.includes('narrow'))construction='RCC frame + masonry infill';let floors=context==='urban'?weighted(r,[1,2,3,4,5,6],[2,20,31,25,16,6]):context==='semiUrban'?weighted(r,[1,2,3,4,5],[25,35,24,12,4]):weighted(r,[1,2,3],[57,38,5]);if(family.includes('narrow'))floors=3+Math.floor(r()*4);if(family==='apartment')floors=4+Math.floor(r()*5);if(construction.includes('stone')||construction.includes('earthen'))floors=Math.min(floors,2);let roof=construction.includes('RCC')?weighted(r,ROOFS.slice(0,3),[5,2,2]):geography==='Terai'?weighted(r,['wide gable','corrugated pitched','tile pitched','hipped','thatch'],[2,4,2,2,1]):weighted(r,ROOFS.slice(3),[2,2,2,4,2,1,1,1]);const use=family.includes('shop')?'mixed residential-commercial':family.includes('workshop')?'workshop':family.includes('warehouse')?'storage':family.includes('lodge')?'hospitality':family.includes('institution')?'institutional':family.includes('agricultural')||family.includes('shed')?'agricultural':pick(r,USES.slice(0,7));let width=family.includes('narrow')?'narrow':family.includes('Terai')||family.includes('warehouse')?'wide':pick(r,['narrow','medium','medium','wide']);return{id:`BLDG-${String(index+1).padStart(3,'0')}`,seed,context,geography,use,construction,family,floors,width,massing:family.includes('hybrid')?pick(r,['two connected blocks','side extension','stacked incremental']):pick(r,MASSINGS),perspective:weighted(r,['front','three-quarter left','three-quarter right','side','loose axonometric'],[35,35,20,5,5]),roof,finish:construction.includes('stone')?'stone':construction.includes('earthen')?'earth plaster':pick(r,FINISHES),window:family.includes('Newar')?'traditional rhythm':pick(r,WINDOWS),balcony:geography==='Terai'?pick(r,['deep verandah','partial verandah']):pick(r,BALCONIES),constructionState:family.includes('incremental')||family.includes('construction')?pick(r,STATES.slice(1)):pick(r,STATES),age:pick(r,AGES),maintenance:pick(r,MAINT),additions:[pick(r,additions),chance(r,.28)?pick(r,additions.slice(1)):'none'].filter(x=>x!=='none'),lineVariation:.12+r()*.2};}
const rp=(pts,r,close=false)=>roughPath(pts,r,{close,jitter:1.6}),path=(d,a='')=>svgPath(d,a,{fill:'none',stroke:INK});
function renderBuilding(b,{paper=false,label=false}={}){const r=seededRandom(b.seed+'draw'),W=240,H=230,base=204;let bw=b.width==='narrow'?72:b.width==='wide'?145:108,bh=Math.min(172,35+b.floors*27),x=120-bw/2,y=base-bh,depth=b.perspective.includes('three-quarter')||b.perspective.includes('axonometric')?24:0,dir=b.perspective.includes('right')?-1:1;let s=`<svg xmlns="${SVG_NS}" viewBox="0 0 ${W} ${H}"><rect width="100%" height="100%" fill="${paper?'#eee9dc':'transparent'}"/><g stroke-linejoin="round" stroke-linecap="round">`;
const wall=rp([[x,base],[x+(r()-.5)*3,y],[x+bw,y+(r()-.5)*3],[x+bw,base]],r,true);let wash=b.finish==='exposed brick'?'#9a6b55':b.finish==='stone'?'#8c8b7d':b.finish==='earth plaster'?'#aa8969':'none';if(wash!=='none')s+=path(wall,`fill="${wash}" fill-opacity=".22" stroke="none"`);s+=path(wall,`stroke-width="${2.5+b.lineVariation*3}"`);if(depth){const dx=depth*dir;s+=path(rp([[x+bw,y],[x+bw+dx,y-12],[x+bw+dx,base-8],[x+bw,base]],r,true),`fill="#7b7064" fill-opacity=".08" stroke-width="2.1"`);s+=path(rp([[x,y],[x+dx,y-12],[x+bw+dx,y-12],[x+bw,y]],r,true),`stroke-width="2"`)}
const pitched=!b.roof.startsWith('flat');if(pitched){const peak=x+bw*.48,yPeak=y-(b.roof.includes('steep')?34:22);s+=path(rp([[x-5,y],[peak,yPeak],[x+bw+5,y]],r),`stroke-width="2.8"`);if(b.roof.includes('corrugated')||b.roof.includes('slate')||b.roof.includes('tile'))for(let k=0;k<7;k++){const xx=x+8+k*(bw-16)/6;s+=path(rp([[xx,y-2],[peak+(xx-peak)*.68,yPeak+(y-yPeak)*.68]],r),`stroke-width=".8"`)}}else{s+=path(rp([[x-3,y],[x-3,y-7],[x+bw+3,y-6],[x+bw+3,y]],r),`stroke-width="2.4"`);if(b.additions.includes('water tank')||chance(r,.28)&&b.context!=='rural')s+=`<ellipse cx="${x+bw*.72}" cy="${y-15}" rx="9" ry="5" fill="none" stroke="${INK}" stroke-width="1.5"/><path d="M ${x+bw*.63} ${y-15}v12h18v-12" fill="none" stroke="${INK}"/>`}
const floorH=bh/b.floors;for(let f=0;f<b.floors;f++){const fy=base-(f+.55)*floorH;if(f>0)s+=path(rp([[x+3,base-f*floorH],[x+bw-3,base-f*floorH]],r),`stroke-width=".65" stroke-opacity=".35"`);let openings=b.width==='narrow'?2:3;if(f===0&&b.use.includes('commercial')||f===0&&b.use==='workshop'||f===0&&b.use==='storage'){for(let o=0;o<(b.width==='wide'?3:2);o++){const ox=x+7+o*(bw-10)/(b.width==='wide'?3:2),ow=(bw-18)/(b.width==='wide'?3:2);s+=path(rp([[ox,base-4],[ox,base-floorH+7],[ox+ow,base-floorH+7],[ox+ow,base-4]],r,true),`stroke-width="1.8"`);for(let q=1;q<5;q++)s+=path(rp([[ox+2,base-q*(floorH-11)/5],[ox+ow-2,base-q*(floorH-11)/5]],r),`stroke-width=".65"`)}}else for(let o=0;o<openings;o++){const ow=10+(r()*4),oh=10+(r()*7),ox=x+(o+1)*bw/(openings+1)-ow/2+(r()-.5)*3;const oy=fy-oh/2;s+=path(rp([[ox,oy],[ox+ow,oy],[ox+ow,oy+oh],[ox,oy+oh]],r,true),`stroke-width="1.6"`);if(b.window==='traditional rhythm')for(let q=1;q<3;q++)s+=path(rp([[ox+q*ow/3,oy],[ox+q*ow/3,oy+oh]],r),`stroke-width=".65"`)}}
if(b.floors>1&&b.balcony!=='none'&&chance(r,.72)){const balconyFloor=1+Math.floor(r()*(b.floors-1)),by=base-balconyFloor*floorH+5;s+=path(rp([[x+5,by],[x+bw-5,by]],r),`stroke-width="2.2"`);for(let q=0;q<6;q++){const qx=x+8+q*(bw-16)/5;s+=path(rp([[qx,by],[qx,by-9]],r),`stroke-width=".8"`)}}
if(['exposed brick','stone','unfinished masonry'].includes(b.finish))for(let k=0;k<7;k++){const tx=x+5+r()*(bw-18),ty=y+8+r()*(bh-18);s+=path(rp([[tx,ty],[tx+8+r()*6,ty+(r()-.5)*2]],r),`stroke-width=".7" stroke-opacity=".55"`)}if(b.constructionState.includes('unfinished')||b.constructionState.includes('vertical'))for(let k=0;k<5;k++){const rx=x+8+k*(bw-16)/4;s+=path(rp([[rx,y-3],[rx,y-14-r()*7]],r),`stroke-width="1"`)}if(b.additions.includes('metal awning'))s+=path(rp([[x-4,base-floorH+5],[x+bw*.55,base-floorH+2],[x+bw*.48,base-floorH+12]],r,true),`fill="#526a79" fill-opacity=".2" stroke-width="1.5"`);s+=path(rp([[x-12,base+5],[x+bw+depth*dir+12,base+5]],r),`stroke-width=".8" stroke-opacity=".5"`);s+=`</g>${label?`<text x="6" y="224" font-size="7" font-family="monospace" fill="${INK}" opacity=".55">${b.id}</text>`:''}</svg>`;return s}
function similarity(a,b){const keys=['context','family','massing','roof','floors','width','construction','window','balcony'];return keys.filter(k=>a[k]===b[k]).length/keys.length}
function population(offset=0){const out=[];for(let i=0;i<240;i++){let tries=0,c;do{c=building(`building-nepal-${offset}-${i}-${tries}`,i);tries++}while(out.some(x=>similarity(x,c)>.82)&&tries<100);out.push(c)}return out}
function posterSVG(list,cols=15){const cw=240,ch=230,m=15,rows=Math.ceil(list.length/cols);return`<svg xmlns="${SVG_NS}" viewBox="0 0 ${cols*cw+m*2} ${rows*ch+m*2}"><rect width="100%" height="100%" fill="#eee9dc"/>${list.map((b,i)=>`<g transform="translate(${m+i%cols*cw} ${m+Math.floor(i/cols)*ch})">${renderBuilding(b,{label:true}).replace(/^<svg[^>]*>|<\/svg>$/g,'')}</g>`).join('')}</svg>`}
export{building,renderBuilding,population,similarity,posterSVG};
if(typeof document!=='undefined'){let list=population(0),selected,offset=0;for(const v of CONSTRUCTIONS)$('#construction').insertAdjacentHTML('beforeend',`<option>${v}</option>`);for(const v of USES)$('#use').insertAdjacentHTML('beforeend',`<option>${v}</option>`);const toast=t=>{$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),1500)};function draw(){const f=list.filter(b=>($('#context').value==='all'||b.context===$('#context').value)&&($('#construction').value==='all'||b.construction===$('#construction').value)&&($('#use').value==='all'||b.use===$('#use').value));$('#count').textContent=f.length;$('#gallery').innerHTML=f.map(b=>`<button class="building" data-id="${b.id}">${renderBuilding(b)}<small>${b.id}</small></button>`).join('')}function open(id){selected=list.find(b=>b.id===id);$('#title').textContent=selected.id;$('#seed').textContent=selected.seed;$('#art').innerHTML=renderBuilding(selected,{paper:true});$('#meta').textContent=JSON.stringify(selected,null,2);const fields={context:CONTEXTS,geography:GEOGRAPHIES,use:USES,construction:CONSTRUCTIONS,roof:ROOFS,massing:MASSINGS,finish:FINISHES,window:WINDOWS,balcony:BALCONIES,constructionState:STATES,age:AGES,maintenance:MAINT};$('#editor').innerHTML=Object.entries(fields).map(([k,a])=>`<label>${k}<select data-field="${k}">${a.map(v=>`<option ${selected[k]===v?'selected':''}>${v}</option>`).join('')}</select></label>`).join('');$('#viewer').showModal()}$('#gallery').onclick=e=>{const b=e.target.closest('[data-id]');if(b)open(b.dataset.id)};$('#close').onclick=()=>$('#viewer').close();$('#editor').onchange=e=>{selected[e.target.dataset.field]=e.target.value;open(selected.id);draw()};document.querySelectorAll('.filters select').forEach(x=>x.onchange=draw);$('#restore').onclick=()=>{list=population(0);draw()};$('#randomize').onclick=()=>{list=population(++offset);draw();toast('New building catalogue generated')};$('#compare').onclick=()=>$('#gallery').classList.toggle('compare');$('#poster').onclick=()=>downloadText('buildings-nepal-240.svg',posterSVG(list));$('#svg').onclick=()=>downloadText(`${selected.id}.svg`,renderBuilding(selected,{paper:false,label:true}));$('#png').onclick=()=>downloadSvgAsPng(`${selected.id}.png`,renderBuilding(selected),1920,1840);$('#regen').onclick=()=>{const i=list.indexOf(selected);list[i]=selected=building(`${selected.seed}-${Date.now()}`,i);open(selected.id);draw()};draw()}
