export const RECIPES={
  denseLane:{label:'Dense residential lane',context:'dense urban',geography:'inner valley',topography:'gentle slope',pattern:'dense contiguous',density:82,urbanization:92,traditional:28,activity:44,vegetation:22,formality:62,mobility:55,roadSurface:'aged asphalt'},
  historicValley:{label:'Historic Valley street',context:'historic urban',geography:'inner valley',topography:'gentle slope',pattern:'courtyard',density:76,urbanization:58,traditional:88,activity:48,vegetation:18,formality:45,mobility:22,roadSurface:'brick paving'},
  urbanCommercial:{label:'Urban commercial street',context:'dense urban',geography:'inner valley',topography:'flat',pattern:'market street',density:90,urbanization:94,traditional:18,activity:86,vegetation:14,formality:68,mobility:78,roadSurface:'asphalt'},
  quietUrban:{label:'Quiet urban neighborhood',context:'urban residential',geography:'inner valley',topography:'gentle slope',pattern:'compound-based',density:58,urbanization:84,traditional:25,activity:20,vegetation:48,formality:75,mobility:34,roadSurface:'asphalt'},
  periHill:{label:'Semi-urban hill corridor',context:'semi-urban / peri-urban',geography:'mid hill',topography:'moderate slope',pattern:'ribbon development',density:54,urbanization:62,traditional:44,activity:48,vegetation:42,formality:38,mobility:58,roadSurface:'aged asphalt'},
  constructionCorridor:{label:'Semi-urban construction corridor',context:'semi-urban / peri-urban',geography:'mid hill',topography:'gentle slope',pattern:'linear roadside',density:62,urbanization:72,traditional:28,activity:58,vegetation:24,formality:26,mobility:66,roadSurface:'mixed surface'},
  hillBazaar:{label:'Small hill bazaar',context:'small town / bazaar',geography:'mid hill',topography:'moderate slope',pattern:'market street',density:72,urbanization:58,traditional:52,activity:72,vegetation:30,formality:48,mobility:52,roadSurface:'aged asphalt'},
  teraiBazaar:{label:'Terai market street',context:'Terai settlement',geography:'Terai',topography:'flat',pattern:'market street',density:70,urbanization:64,traditional:42,activity:78,vegetation:38,formality:46,mobility:70,roadSurface:'asphalt'},
  ruralHill:{label:'Rural hill settlement',context:'rural settlement',geography:'mid hill',topography:'terraced hillside',pattern:'clustered',density:30,urbanization:24,traditional:72,activity:24,vegetation:70,formality:42,mobility:18,roadSurface:'gravel'},
  agricultural:{label:'Rural agricultural road',context:'rural agricultural',geography:'Terai',topography:'flat',pattern:'scattered',density:18,urbanization:20,traditional:58,activity:28,vegetation:82,formality:36,mobility:34,roadSurface:'compacted earth'},
  mountainRoad:{label:'Mountain roadside settlement',context:'mountain settlement',geography:'mountain',topography:'road cut',pattern:'terraced hillside',density:26,urbanization:22,traditional:68,activity:20,vegetation:66,formality:34,mobility:26,roadSurface:'aged asphalt'},
  reconstruction:{label:'Reconstruction settlement',context:'post-disaster / reconstruction',geography:'mid hill',topography:'moderate slope',pattern:'clustered',density:42,urbanization:48,traditional:46,activity:38,vegetation:44,formality:55,mobility:32,roadSurface:'gravel'}
};
export const recipeEntries=()=>Object.entries(RECIPES);
