import{downloadText,downloadSvgAsPng}from'../../src/drawing-engine.js';
import{TYPOLOGIES,VIEWS,MODES,INTERVENTIONS,LAYERS,street,renderStreet,transformStreet,prototypeStreets,perspectiveTests,beforeAfter,populations,posterSVG,validateStreet,projectToScreen,cameraFor}from'./street-engine.js';
export{TYPOLOGIES,VIEWS,MODES,INTERVENTIONS,LAYERS,street,street as road,renderStreet,renderStreet as renderRoad,transformStreet,prototypeStreets,perspectiveTests,beforeAfter,populations,posterSVG,validateStreet,projectToScreen,cameraFor};
const inert={insertAdjacentHTML(){},onclick:null,onchange:null,showModal(){},close(){},value:'all',innerHTML:'',textContent:'',style:{}};const $=s=>(typeof document!=='undefined'&&document.querySelector(s))||inert;
if(typeof document!=='undefined')document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="src/upgrade.css">');
if(typeof document!=='undefined'){let offset=0,all=populations(),category='streets',selected=null;const option=v=>`<option value="${v}">${v}</option>`;TYPOLOGIES.forEach(v=>$('#typology').insertAdjacentHTML('beforeend',option(v)));VIEWS.forEach(v=>$('#view').insertAdjacentHTML('beforeend',option(v)));INTERVENTIONS.forEach(v=>$('#intervention').insertAdjacentHTML('beforeend',option(v)));
const filtered=()=>all[category].filter(d=>($('#typology').value==='all'||d.typology===$('#typology').value)&&($('#view').value==='all'||d.view===$('#view').value));
function draw(){category=$('#category').value;const list=filtered();$('#count').textContent=list.length;$('#gallery').innerHTML=list.map(d=>`<button class="street-card" data-id="${d.id}">${renderStreet(d)}<small>${d.typology}<br><em>${d.view} · ${d.config.lanes} lanes · ${d.bands.reduce((n,b)=>n+b.width,0).toFixed(1)}m</em></small></button>`).join('')}
function editor(){const d=selected,checks=validateStreet(d);$('#title').textContent=d.typology;$('#art').innerHTML=renderStreet(d,{paper:true,label:true});$('#meta').textContent=JSON.stringify({...d,validation:checks.length?checks:['passed']},null,2);$('#layers').innerHTML=LAYERS.map(x=>`<label><input type="checkbox" data-layer="${x}" checked>${x}</label>`).join('');$('#locks').innerHTML=Object.keys(d.locks).map(x=>`<label><input type="checkbox" data-lock="${x}" ${d.locks[x]?'checked':''}>${x}</label>`).join('');$('#viewer').showModal()}
$('#gallery').onclick=e=>{const b=e.target.closest('[data-id]');if(!b)return;selected=all[category].find(d=>d.id===b.dataset.id);editor()};$('#close').onclick=()=>$('#viewer').close();$('#layers').onchange=e=>{const g=$('#art').querySelector(`#${e.target.dataset.layer}`);if(g)g.style.display=e.target.checked?'':'none'};$('#locks').onchange=e=>selected.locks[e.target.dataset.lock]=e.target.checked;
$('#apply').onclick=()=>{const old=selected;selected=transformStreet(selected,[$('#intervention').value]);const i=all[category].indexOf(old);if(i>=0)all[category][i]=selected;editor();draw()};$('#mode-apply').onclick=()=>{selected.mode=$('#visual-mode').value;selected.annotations=selected.mode==='urban design'||selected.mode==='diagram';selected.accent=selected.mode!=='sketch';editor();draw()};$('#svg').onclick=()=>downloadText(`${selected.id}.svg`,renderStreet(selected,{label:true}));$('#png').onclick=()=>downloadSvgAsPng(`${selected.id}.png`,renderStreet(selected,{paper:true}),2080,1280);$('#new').onclick=()=>{all=populations(++offset);draw()};$('#export').onclick=()=>downloadText(`roads-${category}.svg`,posterSVG(filtered(),3));['category','typology','view'].forEach(id=>$(`#${id}`).onchange=draw);draw()}
