import{SVG_NS,seededRandom,pick,roughPath,svgPath}from'../../src/drawing-engine.js';

export const TYPOLOGIES=['Nepali urban local street','Nepali commercial street','Nepali bazaar','Nepali semi-urban corridor','Nepali residential street','Terai main street','Hill bazaar','Mountain road','Complete street','Protected-cycle street','Transit street','Shared street','Historic lane','School street','Rural paved road'];
export const VIEWS=['street level','elevated','axonometric','cross-section','section-perspective'];
export const MODES=['sketch','urban design','diagram','before / after'];
export const INTERVENTIONS=['add sidewalks','widen sidewalks','add trees','add cycle lanes','add transit lane','pedestrianize','create shared street','add median','reduce vehicle lanes','add crossings','add street furniture','cover drain','improve drainage','traffic calming'];
export const LAYERS=['terrain','buildings','roadway','curbs','drainage','walking','cycling','median','crossings','vegetation','utilities','furniture','people','mobility','annotations'];
const INK='#292b29',PAPER='#eee9dc',GREEN='#64786a',BLUE='#536f7d',RUST='#9a5f47';
const recipe={
 'Nepali urban local street':{lanes:2,lane:2.8,walk:1.5,drain:.45,frontage:'setback houses',curb:'vertical curb'},
 'Nepali commercial street':{lanes:2,lane:3,walk:2.1,parking:2.1,drain:.4,frontage:'continuous shop frontage',activity:'busy'},
 'Nepali bazaar':{lanes:2,lane:2.65,walk:1.25,drain:.55,frontage:'shop thresholds and awnings',activity:'busy'},
 'Nepali semi-urban corridor':{lanes:2,lane:3.1,walk:1.3,shoulder:1.2,trees:.8,drain:.7,frontage:'irregular mixed frontage'},
 'Nepali residential street':{lanes:2,lane:2.75,walk:1.7,trees:1,drain:.4,frontage:'setback houses'},
 'Terai main street':{lanes:2,lane:3.2,walk:2.1,parking:2.2,trees:1.2,drain:.55,frontage:'verandah shops'},
 'Hill bazaar':{lanes:2,lane:2.6,walk:1.2,trees:.7,drain:.65,frontage:'stepped shop frontage',grade:.07,retaining:true,activity:'busy'},
 'Mountain road':{lanes:2,lane:3,shoulder:.7,drain:.8,frontage:'retaining wall and valley',grade:.09,retaining:true},
 'Complete street':{lanes:2,lane:3,walk:2.8,cycle:1.8,buffer:.65,trees:1.1,median:1.2,drain:.35,frontage:'mixed urban frontage',crossing:true},
 'Protected-cycle street':{lanes:2,lane:3,walk:2.2,cycle:1.8,buffer:.8,trees:.9,drain:.35,frontage:'urban frontage',crossing:true},
 'Transit street':{lanes:4,lane:3.1,walk:2.7,trees:1,median:.8,drain:.35,frontage:'continuous frontage',transit:true,crossing:true},
 'Shared street':{lanes:1,lane:3.8,walk:2,trees:1,drain:.35,frontage:'active shared frontage',shared:true,activity:'active'},
 'Historic lane':{lanes:1,lane:3.2,walk:.9,drain:.35,frontage:'historic continuous frontage',shared:true},
 'School street':{lanes:2,lane:2.75,walk:2.4,trees:1,buffer:.6,drain:.35,frontage:'school wall and gates',crossing:true},
 'Rural paved road':{lanes:2,lane:2.8,shoulder:1,trees:.9,drain:.55,frontage:'fields and houses'}
};
const clone=o=>JSON.parse(JSON.stringify(o));
function bandsFor(c){const b=[],add=(type,width,side,meta={})=>width&&b.push({type,width,side,...meta});add('frontage',3,'left');add('sidewalk',c.walk||0,'left');add('tree zone',c.trees||0,'left');add('cycle lane',c.cycle||0,'left');add('buffer',c.buffer||0,'left');add('parking',c.parking||0,'left');add('drain',c.drain||0,'left');for(let i=0;i<c.lanes;i++)add(c.transit&&i%2===0?'transit lane':'traffic lane',c.lane,'center',{direction:i<c.lanes/2?-1:1});add('median',c.median||0,'center');add('drain',c.drain||0,'right');add('parking',c.parking||0,'right');add('buffer',c.buffer||0,'right');add('cycle lane',c.cycle||0,'right');add('tree zone',c.trees||0,'right');add('sidewalk',c.walk||0,'right');add('frontage',3,'right');let x=-b.reduce((n,a)=>n+a.width,0)/2;for(const a of b){a.x0=x;a.x1=x+a.width;x=a.x1}return b}
export function cameraFor(view='street level',seed='camera'){const r=seededRandom(seed),height=view==='elevated'||view==='section-perspective'?6.5:view==='urban design'?10:1.65;return{view,width:520,height:320,position:{x:(r()-.5)*.45,y:-9,z:height},target:{x:(r()-.5)*1.4,y:42,z:view==='street level'?1.45:1.1},focalLength:view==='street level'?430:390,fieldOfView:view==='street level'?52:58,principal:{x:260,y:view==='street level'?150:142}}}
export function groundHeight(x,y,model={}){const grade=model.grade||0;return grade*y+(model.terraces?Math.floor(Math.max(0,y)/12)*.35:0)}
const norm=v=>{const n=Math.hypot(v.x,v.y,v.z)||1;return{x:v.x/n,y:v.y/n,z:v.z/n}},cross=(a,b)=>({x:a.y*b.z-a.z*b.y,y:a.z*b.x-a.x*b.z,z:a.x*b.y-a.y*b.x}),dot=(a,b)=>a.x*b.x+a.y*b.y+a.z*b.z;
export function projectPoint(p,c){const wp={...p,z:p.z+groundHeight(p.x,p.y,c.groundModel)};if(c.view==='cross-section')return{x:260+wp.x*15,y:245-wp.z*15,depth:wp.y,visible:true};if(c.view==='axonometric')return{x:260+wp.x*13-wp.y*2.7,y:232-wp.z*12-wp.y*1.7,depth:wp.y,visible:wp.y>=0};const forward=norm({x:c.target.x-c.position.x,y:c.target.y-c.position.y,z:c.target.z-c.position.z}),right=norm(cross(forward,{x:0,y:0,z:1})),up=cross(right,forward),rel={x:wp.x-c.position.x,y:wp.y-c.position.y,z:wp.z-c.position.z},depth=dot(rel,forward);if(depth<=.15)return{x:0,y:0,depth,visible:false};const sx=dot(rel,right),sy=dot(rel,up),f=c.focalLength;return{x:c.principal.x+sx*f/depth,y:c.principal.y-sy*f/depth,depth,visible:true}}
export const projectToScreen=projectPoint;
export function street(seed,index=0,forced={}){const r=seededRandom(seed),typology=forced.typology||TYPOLOGIES[index%TYPOLOGIES.length],config={...recipe[typology]};for(const k of ['lane','walk','cycle','buffer','median','trees','drain','shoulder'])if(config[k])config[k]*=.94+r()*.12;const view=forced.view||pick(r,['street level','street level','elevated','section-perspective']);const mode=forced.mode||'sketch',alignment=forced.alignment||pick(r,['straight','straight','slight bend','moderate bend']),surface=forced.surface||pick(r,['asphalt','aged asphalt','concrete','stone paving','gravel']),bands=bandsFor(config);return{id:`STREET-${String(index+1).padStart(3,'0')}`,seed,typology,view,mode,config,bands,camera:cameraFor(view,seed),alignment,surface,roadForegroundShare:.32+r()*.18,density:forced.density||pick(r,['low','medium','medium','high']),annotations:forced.annotations??mode==='urban design',accent:forced.accent??mode==='urban design',locks:{geometry:false,buildings:false,vegetation:false,mobility:false,streetDesign:false},interventions:[],validation:[]}}
export function transformStreet(source,interventions=['complete street']){const d=clone(source),c=d.config;for(const n of interventions){if(n==='complete street'){Object.assign(c,{walk:2.8,cycle:1.8,buffer:.7,trees:1.1,drain:.35,crossing:true});c.lanes=Math.min(2,c.lanes)}if(n==='add sidewalks')c.walk=Math.max(1.8,c.walk||0);if(n==='widen sidewalks')c.walk=Math.max(2.8,c.walk||0);if(n==='add trees')c.trees=Math.max(1,c.trees||0);if(n==='add cycle lanes')c.cycle=Math.max(1.8,c.cycle||0);if(n==='add transit lane'){c.transit=true;c.lanes=Math.max(2,c.lanes)}if(n==='pedestrianize'){c.shared=true;c.lanes=1;c.lane=3.2;c.walk=2.5}if(n==='create shared street'){c.shared=true;c.lanes=1;c.lane=3.8;c.walk=2}if(n==='add median')c.median=Math.max(1.1,c.median||0);if(n==='reduce vehicle lanes')c.lanes=Math.max(1,c.lanes-2);if(n==='add crossings')c.crossing=true;if(n==='cover drain')c.coveredDrain=true;if(n==='improve drainage')c.drain=Math.max(.55,c.drain||0);if(n==='traffic calming')c.calmed=true}d.bands=bandsFor(c);d.interventions=[...interventions];d.id=source.id+'-PROPOSED';d.mode='urban design';d.accent=true;return d}
const path=(pts,r,attrs='',j=.75)=>svgPath(roughPath(pts,r,{close:attrs.includes('data-close'),jitter:j}),attrs.replace('data-close',''),{fill:'none',stroke:INK});
const poly=(pts,r,attrs='')=>path(pts,r,`${attrs} data-close`);
function bandPolygon(b,c,y0=10,y1=72,z=0){return[projectToScreen({x:b.x0,y:y0,z},c),projectToScreen({x:b.x1,y:y0,z},c),projectToScreen({x:b.x1,y:y1,z},c),projectToScreen({x:b.x0,y:y1,z},c)].map(p=>[p.x,p.y])}
function cleanLine(a,b,c){const p=projectToScreen(a,c),q=projectToScreen(b,c);return[p.x,p.y,q.x,q.y]}
function personAt(x,y,c,r,accent=false){const feet=projectToScreen({x,y,z:0},c),head=projectToScreen({x,y,z:1.72},c),h=feet.y-head.y;if(h<3)return'';return`<circle cx="${head.x}" cy="${head.y+h*.08}" r="${Math.max(1,h*.07)}" fill="none" stroke="${INK}" stroke-width="${Math.max(.5,h*.035)}"/><path d="${roughPath([[head.x,head.y+h*.18],[feet.x,feet.y-h*.3],[feet.x-h*.12,feet.y],[feet.x,feet.y-h*.3],[feet.x+h*.12,feet.y]],r,{jitter:.4})}" fill="none" stroke="${accent?RUST:INK}" stroke-width="${Math.max(.5,h*.035)}"/>`}
function treeAt(x,y,c,r,lod=2){const foot=projectToScreen({x,y,z:0},c),top=projectToScreen({x,y,z:5.5},c),h=foot.y-top.y;if(h<4)return'';const rad=h*.28,detail=lod>1?7:3;let s=path([[foot.x,foot.y],[top.x,top.y+h*.38]],r,`stroke-width="${Math.max(.6,h*.025)}"`);const pts=[];for(let i=0;i<detail*2;i++){const a=Math.PI*2*i/(detail*2),v=1+(r()-.5)*.22;pts.push([top.x+Math.cos(a)*rad*v,top.y+h*.26+Math.sin(a)*rad*.72*v])}return s+poly(pts,r,`fill="${GREEN}" fill-opacity=".12" stroke-width="${Math.max(.55,h*.018)}"`)}
function vehicleAt(x,y,c,r,type='car',accent=false){const a=projectToScreen({x:x-.8,y,z:.1},c),b=projectToScreen({x:x+.8,y,z:1.45},c),w=Math.abs(b.x-a.x),h=Math.abs(b.y-a.y);if(w<3)return'';return poly([[a.x,a.y],[a.x+w*.1,a.y-h*.55],[a.x+w*.75,a.y-h*.75],[a.x+w,a.y-h*.25],[a.x+w,a.y],[a.x,a.y]],r,`fill="${accent?BLUE:INK}" fill-opacity=".08" stroke-width="${Math.max(.55,w*.018)}"`)}
function facade(side,total,c,r,d){
 const sign=side==='left'?-1:1,x=sign*(total/2-1.5),bazaar=d.typology.includes('bazaar')||d.typology.includes('commercial'),pieces=bazaar?7:5;let s='';
 for(let i=0;i<pieces;i++){
  const y0=5+i*8.5,y1=y0+8,h=d.typology.includes('Mountain')?3.4:5.6+(i%3)*1.3,floors=Math.max(1,Math.round(h/3));
  const q=(y,z)=>projectToScreen({x,y,z},c),a=q(y0,0),b=q(y1,0),bt=q(y1,h),at=q(y0,h);
  s+=poly([[a.x,a.y],[b.x,b.y],[bt.x,bt.y],[at.x,at.y]],r,`fill="${i%2?'#8f755f':'#68747b'}" fill-opacity=".025" stroke-width="${i<2?'1.25':'.75'}"`);
  for(let f=1;f<floors;f++){const p=q(y0,f*3),v=q(y1,f*3);s+=path([[p.x,p.y],[v.x,v.y]],r,`stroke-width="${i<2?'.65':'.4'}" stroke-opacity=".62"`)}
  const door=q(y0+1.3,0),doorT=q(y0+1.3,2.15);s+=path([[door.x,door.y],[doorT.x,doorT.y]],r,`stroke-width="${i<2?'.85':'.45'}"`);
  if(i<4)for(let f=0;f<floors;f++){const w0=q(y0+3.2,f*3+1.15),w1=q(y0+4.8,f*3+1.15),w2=q(y0+4.8,f*3+2.05),w3=q(y0+3.2,f*3+2.05);s+=poly([[w0.x,w0.y],[w1.x,w1.y],[w2.x,w2.y],[w3.x,w3.y]],r,'stroke-width=".45"')}
  if(bazaar&&i<3){const aw0=q(y0+.4,2.45),aw1=q(y0+5.8,2.45),aw2=q(y0+5.5,2.1);s+=path([[aw0.x,aw0.y],[aw1.x,aw1.y],[aw2.x,aw2.y]],r,'stroke-width=".8"')}
 }
 return s
}
export function validateStreet(d){const issues=[];const types=d.bands.map(b=>b.type);if(!types.includes('traffic lane'))issues.push('no vehicle lane');if(d.config.cycle&&!types.includes('cycle lane'))issues.push('cycle discontinuity');if(d.config.walk&&!types.includes('sidewalk'))issues.push('sidewalk discontinuity');if(d.config.crossing&&!d.config.walk)issues.push('crossing lacks pedestrian space');if(d.config.lane<2.7||d.config.lane>3.5)issues.push('traffic lane outside ordinary range');return issues}
export function validatePerspective(d){const c={...d.camera,groundModel:d.config},nearL=projectPoint({x:-d.config.lane,y:8,z:0},c),nearR=projectPoint({x:d.config.lane,y:8,z:0},c),farL=projectPoint({x:-d.config.lane,y:45,z:0},c),farR=projectPoint({x:d.config.lane,y:45,z:0},c),personNear=projectPoint({x:0,y:8,z:1.7},c),personFar=projectPoint({x:0,y:45,z:1.7},c),groundNear=projectPoint({x:0,y:8,z:0},c),groundFar=projectPoint({x:0,y:45,z:0},c);const checks={roadNarrows:Math.abs(farR.x-farL.x)<Math.abs(nearR.x-nearL.x),scaleDecreases:Math.abs(groundFar.y-personFar.y)<Math.abs(groundNear.y-personNear.y),spacingCompresses:Math.abs(projectPoint({x:0,y:35,z:0},c).y-projectPoint({x:0,y:45,z:0},c).y)<Math.abs(projectPoint({x:0,y:8,z:0},c).y-projectPoint({x:0,y:18,z:0},c).y),grounded:true,verticals:true};return{passed:Object.values(checks).every(Boolean),checks}}
export function renderStreet(d,{paper=false,label=false,clean=false}={}){const r=seededRandom(d.seed+'render'),c={...d.camera,view:d.view},W=520,H=320,total=d.bands.reduce((n,b)=>n+b.width,0),accent=d.accent,issues=validateStreet(d);let s=`<svg xmlns="${SVG_NS}" viewBox="0 0 ${W} ${H}"><rect width="100%" height="100%" fill="${paper?PAPER:'transparent'}"/><g id="terrain">`;
 if(d.view==='cross-section')s+=path([[16,246],[504,246]],r,'stroke-width="1"',clean?0:.5);s+=`</g><g id="buildings">${facade('left',total,c,r,d)}${facade('right',total,c,r,d)}</g>`;
 const groups={roadway:'',curbs:'',drainage:'',walking:'',cycling:'',median:'',crossings:'',vegetation:'',utilities:'',furniture:'',people:'',mobility:'',annotations:''};
 for(const b of d.bands){const pts=bandPolygon(b,c),isRoad=b.type.includes('lane')||b.type==='parking',fill=isRoad?'#555b59':b.type==='sidewalk'?'#b8aa91':b.type==='cycle lane'?(accent?BLUE:'#8c9490'):b.type==='tree zone'||b.type==='median'?(accent?GREEN:'#8b9488'):'#777';const target=b.type==='sidewalk'?'walking':b.type==='cycle lane'?'cycling':b.type==='drain'?'drainage':b.type==='median'?'median':'roadway';groups[target]+=poly(pts,r,`fill="${fill}" fill-opacity="${isRoad?'.055':'.09'}" stroke-width="${isRoad?'1.35':'.7'}"`,clean?0:.5);if(['sidewalk','tree zone'].includes(b.type)){const l=cleanLine({x:b.x0,y:4,z:.12},{x:b.x0,y:72,z:.12},c);groups.curbs+=path([[l[0],l[1]],[l[2],l[3]]],r,'stroke-width="1.25"',clean?0:.45)}if(b.type==='drain'){for(let y=8;y<65;y+=8){const p=projectToScreen({x:(b.x0+b.x1)/2,y,z:.02},c);groups.drainage+=`<circle cx="${p.x}" cy="${p.y}" r=".55" fill="${INK}" opacity=".42"/>`}}}
 if(d.config.crossing){const lanes=d.bands.filter(b=>b.type.includes('lane')),x0=Math.min(...lanes.map(b=>b.x0)),x1=Math.max(...lanes.map(b=>b.x1));for(let y=10;y<14;y+=.75)groups.crossings+=poly([projectToScreen({x:x0,y,z:.03},c),projectToScreen({x:x1,y,z:.03},c),projectToScreen({x:x1,y:y+.35,z:.03},c),projectToScreen({x:x0,y:y+.35,z:.03},c)].map(p=>[p.x,p.y]),r,`fill="${accent?RUST:INK}" fill-opacity=".16" stroke-width=".25"`)}
 const treeBands=d.bands.filter(b=>b.type==='tree zone');for(const b of treeBands)for(const y of [7,14,23,35,51])groups.vegetation+=treeAt((b.x0+b.x1)/2,y,c,r,y<14?3:y<30?2:1);
 const sidewalks=d.bands.filter(b=>b.type==='sidewalk');for(const [i,b] of sidewalks.entries())for(const y of [8+i*3,17+i*5,31])groups.people+=personAt((b.x0+b.x1)/2,y,c,r);
 const lanes=d.bands.filter(b=>b.type.includes('lane'));for(let i=0;i<Math.min(4,lanes.length+1);i++){const b=lanes[i%lanes.length];if(b)groups.mobility+=vehicleAt((b.x0+b.x1)/2,9+i*10,c,r,i===3?'bus':'car',d.config.transit&&b.type==='transit lane')}
 if(d.density!=='low'){for(const b of sidewalks.slice(0,2))for(const y of [9,24,43]){const p=projectToScreen({x:(b.x0+b.x1)/2,y,z:0},c),q=projectToScreen({x:(b.x0+b.x1)/2,y,z:5.2},c);groups.utilities+=path([[p.x,p.y],[q.x,q.y]],r,'stroke-width=".8"')}}
 if(d.annotations){for(const b of d.bands.filter(b=>['sidewalk','cycle lane','median','tree zone','transit lane'].includes(b.type))){const p=projectToScreen({x:(b.x0+b.x1)/2,y:8,z:.1},c);groups.annotations+=`<text x="${p.x}" y="${p.y}" font-size="5" font-family="ui-monospace,monospace" text-anchor="middle" fill="${accent?RUST:INK}">${b.type.toUpperCase()}</text>`}}
 for(const name of Object.keys(groups))s+=`<g id="${name}">${groups[name]}</g>`;s+=label?`<text x="10" y="308" font-size="7" font-family="ui-monospace,monospace" fill="${INK}">${d.typology} · ${d.view}${issues.length?' · CHECK '+issues.join(', '):''}</text>`:'';return s+'</svg>'}
export function prototypeStreets(offset=0){return TYPOLOGIES.slice(0,12).map((typology,i)=>street(`road-prototype-${offset}-${i}`,i,{typology,view:i%4===0?'elevated':'street level'}))}
export function perspectiveTests(seed='perspective-test'){const base=street(seed,8,{typology:'Complete street'});return VIEWS.slice(0,4).map(view=>({...clone(base),id:`${base.id}-${view}`,view,camera:cameraFor(view,seed)}))}
export function beforeAfter(seed='before-after'){const existing=street(seed,5,{typology:'Nepali semi-urban corridor',view:'elevated'});return[existing,transformStreet(existing,['complete street','add crossings','add street furniture'])]}
export function populations(offset=0){return{streets:Array.from({length:120},(_,i)=>street(`street-nepal-${offset}-${i}`,i)),intersections:Array.from({length:30},(_,i)=>street(`junction-${offset}-${i}`,i,{typology:i%2?'Nepali commercial street':'Nepali urban local street',view:'elevated'})),sections:Array.from({length:45},(_,i)=>street(`section-${offset}-${i}`,i,{view:i%2?'cross-section':'section-perspective'})),beforeAfter:Array.from({length:24},(_,i)=>beforeAfter(`transform-${offset}-${i}`)).flat()}}
export function posterSVG(list,cols=3){const cw=520,ch=320,m=10,rows=Math.ceil(list.length/cols);return`<svg xmlns="${SVG_NS}" viewBox="0 0 ${cols*cw+m*2} ${rows*ch+m*2}"><rect width="100%" height="100%" fill="${PAPER}"/>${list.map((d,i)=>`<g transform="translate(${m+i%cols*cw} ${m+Math.floor(i/cols)*ch})">${renderStreet(d,{label:true}).replace(/^<svg[^>]*>|<\/svg>$/g,'')}</g>`).join('')}</svg>`}
