const $=s=>document.querySelector(s);
const NS='http://www.w3.org/2000/svg';
const HEADS=['round','wide round','narrow oval','long oval','egg','square','soft rectangle','pear','inverted pear','wide jaw','narrow jaw','large forehead','flat crown','asymmetric','angular'];
const NOSES=['long straight','short straight','wide triangular','hooked','rounded tip','long narrow','flat bridge','strong bridge','button','downturned','upturned','angular','curving','wide nostrils','thin nostrils','asymmetric','prominent profile','large rounded','short angular','long crooked'];
const EYES=['dot','small circle','large circle','almond','half closed','curved line','tiny oval','heavy lid','surprised','narrow','uneven'];
const MOUTHS=['line','slight smile','wide smile','downturned','open','thin lips','full minimal','small curve','uneven','side smile','pressed','teeth','upper lip','lower lip'];
const HAIR=['buzz cut','side part','short messy','crew cut','flat top','short curly','close cropped','receding','widow peak','balding','shaved sides','short fringe','side swept','messy waves','curly','layered','middle part','long fringe','long straight','long wavy','low ponytail','high ponytail','braid','two braids','bun','messy bun','half tied','shoulder length','mostly bald','sparse'];
const EXPRESSIONS=['neutral','slight smile','wide smile','serious','skeptical','curious','tired','concerned','calm','confident','shy','amused','annoyed','surprised','thoughtful'];
const AGES=['18–25','26–40','41–55','56–70','70+']; const ORIENT=['front','three-quarter left','three-quarter right','profile left','profile right'];
const GLASSES=['none','small round','large round','thin rectangular','thick rectangular','square','half rim','oversized','reading','sunglasses'];
const HATS=['none','none','none','none','Dhaka topi','black topi','knit cap','beanie','sun cap','baseball cap','head scarf','shawl'];
const FACIAL=['none','none','none','thin moustache','thick moustache','stubble','goatee','short beard','full beard'];
const CLOTHES=['shirt collar','T-shirt','sweater','jacket','coat','hoodie','kurta neckline','shawl','office shirt','traditional vest'];
const ACCENTS=['#A4513F','#445D72','#C08A36','#69745B','#B97755'];
const FACE_WASHES=['#D6A27B','#C98E6B','#D2B47F','#B8A686','#B98162'];
const BACKDROPS=['#AEBEB8','#BCC9D7','#C8BDD1','#C6C59E','#B9C8B6','#D3C3B8'];
const WOMEN_HAIR=['short fringe','side swept','short curly','layered','middle part','long fringe','long straight','long wavy','low ponytail','high ponytail','braid','two braids','bun','messy bun','half tied','shoulder length'];
const ACCESSORIES=['none','none','small earrings','drop earrings','nose stud','small bindi','hair clip'];
function hash(x){let h=2166136261;for(const c of String(x)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function rng(seed){let a=hash(seed);return()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
const pick=(r,a)=>a[Math.floor(r()*a.length)], chance=(r,p)=>r()<p, clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function character(seed,i=0){const r=rng(seed);const gender=i%50===0?'ambiguous':i%2?'woman':'man';let age=pick(r,AGES);const c={id:`NEP-${String(i+1).padStart(3,'0')}`,seed,genderPresentation:gender,ageGroup:age,orientation:pick(r,ORIENT),headShape:pick(r,HEADS),noseType:pick(r,NOSES),eyeType:pick(r,EYES),mouthType:pick(r,MOUTHS),hairstyle:pick(r,HAIR),expression:pick(r,EXPRESSIONS),glasses:chance(r,.12)?pick(r,GLASSES.slice(1)):'none',headwear:chance(r,.13)?pick(r,HATS.slice(4)):'none',facialHair:gender==='man'&&chance(r,.38)?pick(r,FACIAL.slice(3)):'none',clothingCue:pick(r,CLOTHES),lineVariation:.12+r()*.18,lean:(r()-.5)*8,accentColor:chance(r,.42)?pick(r,ACCENTS):'none',accentUse:pick(r,['clothing','clothing','headwear','small detail']),faceWash:chance(r,.38)?pick(r,FACE_WASHES):'none',colorHair:chance(r,.11)?pick(r,['#445D72','#69745B','#8B5C46']):'none',backdrop:chance(r,.46)?pick(r,BACKDROPS):'none',rosyCheeks:chance(r,.20),accessory:'none'};if(gender==='woman'){c.hairstyle=pick(r,WOMEN_HAIR);c.accessory=pick(r,ACCESSORIES);c.clothingCue=pick(r,['kurta neckline','shawl','office shirt','sweater','jacket','T-shirt','coat']);if(i%12===1)c.hairstyle='bun'}if(i%18===0)c.orientation=i%36?'profile left':'profile right';if(i%16===0)c.glasses='large round';if(i%19===0){c.headwear='Dhaka topi';c.accentColor=pick(r,ACCENTS);c.accentUse='headwear'}return c}
function pointPath(points,r,close=false){let d=`M ${points[0][0].toFixed(1)} ${points[0][1].toFixed(1)}`;for(let i=1;i<points.length;i++){const p=points[i];d+=` L ${(p[0]+(r()-.5)*1.5).toFixed(1)} ${(p[1]+(r()-.5)*1.5).toFixed(1)}`}return d+(close?' Z':'')}
function ellipsePath(cx,cy,rx,ry,r,n=24){const pts=[];for(let i=0;i<n;i++){const a=Math.PI*2*i/n,noise=1+(r()-.5)*.055;pts.push([cx+Math.cos(a)*rx*noise,cy+Math.sin(a)*ry*noise])}return pointPath(pts,r,true)}
const path=(d,extra='')=>`<path d="${d}" ${extra.includes('fill=')?'':'fill="none" '}${extra.includes('stroke=')?'':'stroke="#25262a" '}${extra}/>`;
function portrait(c,{paper=false,label=false}={}){const r=rng(c.seed+'draw');let w=84+(HEADS.indexOf(c.headShape)%5)*5,h=102+(HEADS.indexOf(c.headShape)%4)*5;if(c.headShape.includes('wide'))w+=16;if(c.headShape.includes('narrow')||c.headShape==='long oval')w-=9;const cx=100+(c.orientation.includes('left')?5:c.orientation.includes('right')?-5:0),cy=105;const xL=cx-w/2,xR=cx+w/2,yT=cy-h/2,yB=cy+h/2;const sw=3.15+c.lineVariation*3,ink='#25262a',blob=c.backdrop&&c.backdrop!=='none'?ellipsePath(cx+(r()-.5)*8,cy+5,w*.67,h*.59,r,18):null;let s=`<svg xmlns="${NS}" viewBox="0 0 200 220" role="img" aria-label="${c.id}, ${c.ageGroup}, ${c.orientation}"><rect width="200" height="220" fill="${paper?'#eee9dc':'transparent'}"/>${blob?`<path d="${blob}" fill="${c.backdrop}" fill-opacity=".44" stroke="none"/>`:''}<g transform="rotate(${c.lean} 100 110)" fill="none" stroke="${ink}" stroke-width="${sw.toFixed(2)}" stroke-linecap="round" stroke-linejoin="round">`;
 const head=ellipsePath(cx,cy,w/2,h/2,r,30);if(c.faceWash&&c.faceWash!=='none'){s+=path(head,`fill="${c.faceWash}" fill-opacity=".42" stroke="none"`);for(let k=-2;k<3;k++){const yy=cy+k*13,half=w*.42*Math.sqrt(Math.max(0,1-Math.pow((yy-cy)/(h/2),2)));s+=path(pointPath([[cx-half,yy+7],[cx+half,yy-7]],r),`stroke="#eee9dc" stroke-opacity=".62" stroke-width="2.2"`)}}s+=path(head);const profile=c.orientation.includes('profile'),dir=c.orientation.includes('left')?-1:1;
 if(!profile){s+=path(ellipsePath(xL-1,cy+2,6,11,r,12));s+=path(ellipsePath(xR+1,cy+1,6,10,r,12));s+=path(pointPath([[xL-2,cy-2],[xL+1,cy+2],[xL-2,cy+6]],r),`stroke="${ink}" stroke-width="1.35"`);s+=path(pointPath([[xR+2,cy-2],[xR-1,cy+2],[xR+2,cy+6]],r),`stroke="${ink}" stroke-width="1.35"`)}else{s+=path(ellipsePath(cx-dir*w/2,cy+2,5,10,r,10))}
 const eyeY=cy-10+(r()-.5)*4,sep=20+(r()-.5)*8;function eye(x,y,scale=1){if(['half closed','curved line','narrow'].includes(c.eyeType))return path(pointPath([[x-7*scale,y],[x,y+(c.expression==='tired'?2:-2)],[x+7*scale,y]],r));let rx=c.eyeType==='large circle'||c.eyeType==='surprised'?7:5,ry=c.eyeType==='narrow'?2.5:4;return path(ellipsePath(x,y,rx*scale,ry,r,10))+`<circle cx="${x+(r()-.5)*2}" cy="${y}" r="${c.eyeType==='dot'?1.5:2.1}" fill="${ink}" stroke="none"/>`}
 if(profile){s+=eye(cx+dir*11,eyeY,1)}else{s+=eye(cx-sep,eyeY+(r()-.5)*3,.9+r()*.15)+eye(cx+sep,eyeY+(r()-.5)*3,.9+r()*.15)}if(c.genderPresentation==='woman'&&hash(c.seed+'lashes')%100<58){const lash=`stroke="${ink}" stroke-width="1.35"`;s+=path(pointPath([[cx-sep-5,eyeY-2],[cx-sep-8,eyeY-6]],r),lash);if(!profile)s+=path(pointPath([[cx+sep+5,eyeY-2],[cx+sep+8,eyeY-6]],r),lash)}if(c.rosyCheeks){const blush='#C98278';s+=`<ellipse cx="${cx-sep-2}" cy="${eyeY+23}" rx="7" ry="4.5" fill="${blush}" fill-opacity=".42" stroke="none"/>`;if(!profile)s+=`<ellipse cx="${cx+sep+2}" cy="${eyeY+23}" rx="7" ry="4.5" fill="${blush}" fill-opacity=".42" stroke="none"/>`}
 const noseLen=18+(NOSES.indexOf(c.noseType)%6)*3,nx=cx+(profile?dir*10:0),ny=eyeY+3;let nosePts=profile?[[nx,ny],[nx+dir*4,ny+10],[nx+dir*(noseLen*.72),ny+18],[nx+dir*8,ny+22],[nx+dir*3,ny+20]]:[[nx,ny],[nx+(r()-.5)*4,ny+noseLen],[nx+dir*6,ny+noseLen+3],[nx+dir*10,ny+noseLen]];s+=path(pointPath(nosePts,r));
 const mouthY=cy+28,smile=['slight smile','wide smile','amused','confident'].includes(c.expression)||c.mouthType.includes('smile'),down=['serious','concerned','annoyed'].includes(c.expression)||c.mouthType==='downturned';let my=smile?3:down?-3:0;s+=path(pointPath([[cx-9,mouthY],[cx,mouthY+my],[cx+10,mouthY]],r));if(c.mouthType==='open'||c.mouthType==='teeth'||c.expression==='surprised')s+=path(ellipsePath(cx,mouthY+2,7,c.expression==='surprised'?6:3,r,10),c.mouthType==='open'?`fill="${ink}"`:'');
 // brows, age marks, and economical observational detail
 s+=path(pointPath([[cx-sep-7,eyeY-9],[cx-sep,eyeY-11],[cx-sep+7,eyeY-9]],r))+(!profile?path(pointPath([[cx+sep-7,eyeY-9],[cx+sep,eyeY-11],[cx+sep+7,eyeY-9]],r)):'');const ageDetail=AGES.indexOf(c.ageGroup),detail=1+Math.floor(r()*3)+(ageDetail>2?1:0),fine=`stroke="${ink}" stroke-width="${(sw*.48).toFixed(2)}" stroke-opacity=".78"`;if(ageDetail>2){s+=path(pointPath([[cx-13,yT+24],[cx-2,yT+22],[cx+10,yT+24]],r),fine);if(ageDetail===4)s+=path(pointPath([[cx-11,yT+30],[cx+9,yT+29]],r),fine)}if(detail>1){s+=path(pointPath([[cx-sep-8,eyeY+7],[cx-sep-2,eyeY+9],[cx-sep+5,eyeY+8]],r),fine);if(!profile)s+=path(pointPath([[cx+sep-6,eyeY+8],[cx+sep+1,eyeY+10],[cx+sep+7,eyeY+7]],r),fine)}if(detail>2){s+=path(pointPath([[nx-5,ny+noseLen-2],[nx,ny+noseLen+2],[nx+5,ny+noseLen]],r),fine);s+=path(pointPath([[cx-22,mouthY-3],[cx-18,mouthY+2]],r),fine);if(!profile)s+=path(pointPath([[cx+21,mouthY-4],[cx+18,mouthY+2]],r),fine)}if(detail>3){s+=path(pointPath([[cx-8,mouthY+10],[cx,mouthY+12],[cx+9,mouthY+9]],r),fine);for(let k=0;k<5;k++){const fx=cx+(r()-.5)*35,fy=cy+12+r()*28;s+=`<circle cx="${fx.toFixed(1)}" cy="${fy.toFixed(1)}" r=".75" fill="${ink}" fill-opacity=".55" stroke="none"/>`}}
 // hair
 const hairBottom=yT+20+(HAIR.indexOf(c.hairstyle)%4)*4;if(!['mostly bald','sparse'].includes(c.hairstyle)){const hd=ellipsePath(cx,yT+9,w*.49,23,r,22),hairFill=c.colorHair&&c.colorHair!=='none'?c.colorHair:ink;s+=path(hd,`fill="${hairFill}" fill-opacity="${hairFill===ink?1:.82}"`);s+=`<path d="M ${xL+4} ${hairBottom} Q ${cx-18} ${hairBottom-8} ${cx} ${hairBottom} T ${xR-3} ${hairBottom-2}" fill="${paper?'#eee9dc':'#f4f0e5'}" stroke="none"/>`;if(hairFill!==ink)for(let k=0;k<5;k++)s+=path(pointPath([[xL+12+k*14,yT-1],[xL+18+k*14,yT+20]],r),`stroke="${ink}" stroke-opacity=".55" stroke-width="1.6"`)}else{for(let k=0;k<8;k++)s+=path(pointPath([[xL+12+k*5,yT+12],[xL+13+k*5,yT+3+r()*6]],r))}
 if(c.hairstyle.includes('curly'))for(let k=0;k<11;k++)s+=path(ellipsePath(xL+8+k*5,yT+8+(k%2)*4,4,4,r,8));if(c.hairstyle.includes('bun'))s+=path(ellipsePath(xR-3,yT+3,14,14,r,16),`fill="${ink}"`);if(['long straight','long wavy','shoulder length','half tied'].includes(c.hairstyle)){const sideL=pointPath([[xL+7,yT+18],[xL-2,cy-5],[xL+2,yB+8],[xL+12,yB+17]],r),sideR=pointPath([[xR-7,yT+18],[xR+3,cy-4],[xR-1,yB+8],[xR-11,yB+17]],r);s+=path(sideL,`stroke="${ink}" stroke-width="6"`)+path(sideR,`stroke="${ink}" stroke-width="6"`);for(let k=0;k<3;k++)s+=path(pointPath([[xL+5+k*3,cy-5],[xL+7+k*2,yB+12]],r),`stroke="#eee9dc" stroke-width="1"`)}if(c.hairstyle.includes('ponytail'))s+=path(ellipsePath(xR+10,yT+34,10,22,r,14),`fill="${ink}"`);if(c.hairstyle.includes('braid')){const sides=c.hairstyle==='two braids'?[-1,1]:[1];for(const side of sides)for(let k=0;k<4;k++)s+=path(ellipsePath(cx+side*(w/2+5),cy+5+k*10,5,7,r,9),`fill="${k%2?ink:'#eee9dc'}"`)}
 if(c.facialHair!=='none'){if(c.facialHair.includes('moustache'))s+=path(pointPath([[cx-13,mouthY-8],[cx,mouthY-4],[cx+13,mouthY-8],[cx,mouthY]],r,true),`fill="${ink}"`);else {const bd=pointPath([[cx-w*.3,cy+24],[cx-w*.22,yB-4],[cx,yB+8],[cx+w*.25,yB-3],[cx+w*.3,cy+25]],r);s+=path(bd,c.facialHair==='stubble'?`stroke-dasharray="1 5"`:`stroke-width="${sw+2}"`)}}
 if(c.glasses!=='none'){const gw=c.glasses.includes('large')||c.glasses==='oversized'?17:13,gh=c.glasses==='thin rectangular'?7:12;s+=path(ellipsePath(cx-sep,eyeY,gw,gh,r,14),c.glasses==='sunglasses'?`fill="${ink}"`:'')+(!profile?path(ellipsePath(cx+sep,eyeY,gw,gh,r,14),c.glasses==='sunglasses'?`fill="${ink}"`:''):'')+path(pointPath([[cx-sep+gw,eyeY],[cx+sep-gw,eyeY]],r))}
 if(c.headwear!=='none'){let cap=pointPath([[xL-2,yT+18],[xL+8,yT-2],[cx,yT-14],[xR-5,yT+2],[xR+2,yT+18]],r),hatColor=c.accentColor!=='none'&&c.accentUse==='headwear'?c.accentColor:'#eee9dc';s+=path(cap,c.headwear==='black topi'?`fill="${ink}"`:`fill="${hatColor}" fill-opacity=".72"`);s+=path(pointPath([[xL,yT+17],[xR,yT+17]],r));if(c.headwear==='Dhaka topi'){for(let k=0;k<5;k++){const xx=xL+10+k*(w-20)/4;s+=path(pointPath([[xx,yT+7],[xx+9,yT+17]],r),`stroke="${k%2?ink:'#eee9dc'}" stroke-width="2"`)}s+=path(pointPath([[xL+8,yT+8],[xR-6,yT+8]],r),`stroke="#eee9dc" stroke-width="2" stroke-dasharray="5 4"`)}}
 if(c.accessory==='small earrings'||c.accessory==='drop earrings'){const drop=c.accessory==='drop earrings'?7:2.5,ac=c.accentColor!=='none'?c.accentColor:'#A4513F';s+=`<circle cx="${xL-1}" cy="${cy+12+drop}" r="${drop>3?3:2.3}" fill="${ac}" fill-opacity=".72" stroke="${ink}" stroke-width="1.2"/>`;if(!profile)s+=`<circle cx="${xR+1}" cy="${cy+12+drop}" r="${drop>3?3:2.3}" fill="${ac}" fill-opacity=".72" stroke="${ink}" stroke-width="1.2"/>`;if(drop>3)s+=path(pointPath([[xL-1,cy+9],[xL-1,cy+16]],r),`stroke="${ink}" stroke-width="1.2"`)}else if(c.accessory==='nose stud')s+=`<circle cx="${nx+dir*7}" cy="${ny+noseLen-3}" r="1.7" fill="#C08A36" stroke="${ink}" stroke-width=".8"/>`;else if(c.accessory==='small bindi')s+=`<circle cx="${cx}" cy="${eyeY-15}" r="2" fill="#A4513F" stroke="none"/>`;else if(c.accessory==='hair clip')s+=path(pointPath([[xR-20,yT+10],[xR-9,yT+15]],r),`stroke="#A4513F" stroke-width="3"`);
 const accent=c.accentColor!=='none'?c.accentColor:null;if(accent&&c.accentUse==='clothing'){const cloth=pointPath([[cx-42,yB+25],[cx-18,yB+13],[cx,yB+22],[cx+18,yB+13],[cx+42,yB+25]],r,true);s+=path(cloth,`fill="${accent}" fill-opacity=".64" stroke="${ink}"`);if(['shawl','traditional vest','kurta neckline'].includes(c.clothingCue))s+=path(pointPath([[cx-34,yB+22],[cx,yB+15],[cx+34,yB+22]],r),`stroke="#eee9dc" stroke-width="3" stroke-dasharray="7 5"`)}else if(accent&&c.accentUse==='small detail'){if(c.genderPresentation==='woman')s+=`<circle cx="${xR+2}" cy="${cy+9}" r="3.2" fill="${accent}" stroke="${ink}" stroke-width="1.4"/>`;else s+=path(pointPath([[cx-8,yB+17],[cx,yB+23],[cx+8,yB+17]],r),`fill="${accent}" fill-opacity=".8"`)}
 s+=path(pointPath([[cx-15,yB-1],[cx-17,yB+19],[cx-42,yB+25]],r))+path(pointPath([[cx+15,yB-1],[cx+17,yB+19],[cx+42,yB+25]],r));s+=`</g>${label?`<text x="8" y="212" font-family="monospace" font-size="7" fill="${ink}" opacity=".55">${c.id}</text>`:''}</svg>`;return s}
function population(offset=0){const out=[];let tries=0;for(let i=0;i<144;i++){let c;do{c=character(`nepal-${offset}-${i}-${tries}`,i);tries++}while(out.some(x=>similarity(x,c)>.8)&&tries<2000);out.push(c)}return out}
function similarity(a,b){const keys=['headShape','noseType','eyeType','hairstyle','orientation','headwear','glasses','expression','facialHair'];return keys.filter(k=>a[k]===b[k]).length/keys.length}
export {character,population,portrait,posterSVGFor,similarity};
function posterSVGFor(list,cols=12){const size=190,margin=18,rows=Math.ceil(list.length/cols),W=size*cols+margin*2,H=size*rows+margin*2;return `<svg xmlns="${NS}" viewBox="0 0 ${W} ${H}"><rect width="100%" height="100%" fill="#eee9dc"/>${list.map((c,i)=>`<g transform="translate(${margin+(i%cols)*size} ${margin+Math.floor(i/cols)*size}) scale(.86)">${portrait(c,{label:true}).replace(/^<svg[^>]*>|<\/svg>$/g,'')}</g>`).join('')}</svg>`}
if(typeof document!=='undefined'){
let people=population(0),selected=null,offset=0;
function render(){const f=people.filter(c=>($('#age-filter').value==='all'||c.ageGroup===$('#age-filter').value)&&($('#gender-filter').value==='all'||c.genderPresentation===$('#gender-filter').value)&&($('#orientation-filter').value==='all'||c.orientation===$('#orientation-filter').value)&&(!$('#glasses-filter').checked||c.glasses!=='none')&&(!$('#headwear-filter').checked||c.headwear!=='none'));$('#visible-count').textContent=f.length;$('#gallery').innerHTML=f.map(c=>`<button class="portrait" data-id="${c.id}" aria-label="Open ${c.id}">${portrait(c)}<span class="id">${c.id}</span></button>`).join('');}
for(const a of AGES)$('#age-filter').insertAdjacentHTML('beforeend',`<option>${a}</option>`);for(const o of ORIENT)$('#orientation-filter').insertAdjacentHTML('beforeend',`<option>${o}</option>`);
function select(id){selected=people.find(c=>c.id===id);$('#viewer-id').textContent=selected.id;$('#viewer-seed').textContent=`Seed · ${selected.seed}`;$('#viewer-art').innerHTML=portrait(selected,{paper:true});$('#metadata').textContent=JSON.stringify(selected,null,2);const fields={genderPresentation:['woman','man','ambiguous'],headShape:HEADS,noseType:NOSES,eyeType:EYES,mouthType:MOUTHS,hairstyle:HAIR,expression:EXPRESSIONS,orientation:ORIENT,accessory:ACCESSORIES,glasses:GLASSES,headwear:[...new Set(HATS)],facialHair:FACIAL};$('#editor').innerHTML=Object.entries(fields).map(([k,v])=>`<label>${k.replace(/[A-Z]/g,m=>' '+m).replace(/^./,m=>m.toUpperCase())}<select data-field="${k}">${v.map(x=>`<option ${selected[k]===x?'selected':''}>${x}</option>`).join('')}</select></label>`).join('');$('#viewer').showModal()}
function refreshSelected(){$('#viewer-art').innerHTML=portrait(selected,{paper:true});$('#metadata').textContent=JSON.stringify(selected,null,2);render()}
$('#gallery').addEventListener('click',e=>{const b=e.target.closest('[data-id]');if(b)select(b.dataset.id)});$('#close').onclick=()=>$('#viewer').close();$('#viewer').addEventListener('click',e=>{if(e.target===$('#viewer'))$('#viewer').close()});$('#editor').addEventListener('change',e=>{selected[e.target.dataset.field]=e.target.value;refreshSelected()});
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),1800)}
$('#generate').onclick=()=>{people=population(0);render();toast('Original seeded population restored')};$('#randomize').onclick=()=>{people=population(++offset);render();toast('A new population was generated')};document.querySelectorAll('.filters input,.filters select').forEach(x=>x.addEventListener('change',render));$('#poster-mode').onclick=()=>$('#gallery').classList.toggle('poster-view');
function download(name,text,type='image/svg+xml'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
$('#poster').onclick=()=>download('nepali-faces-144.svg',posterSVGFor(people));$('#svg-one').onclick=()=>download(`${selected.id}.svg`,portrait(selected,{paper:true,label:true}));$('#regen-one').onclick=()=>{const i=people.indexOf(selected);people[i]=selected=character(`${selected.seed}-r-${Date.now()}`,i);select(selected.id);toast('Character regenerated')};
$('#png-one').onclick=()=>{const svg=portrait(selected,{paper:false}),img=new Image(),canvas=document.createElement('canvas');canvas.width=1600;canvas.height=1760;img.onload=()=>{const c=canvas.getContext('2d');c.drawImage(img,0,0,1600,1760);canvas.toBlob(b=>{const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`${selected.id}.png`;a.click()},'image/png')};img.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg)};
render();
}
