export const SVG_NS='http://www.w3.org/2000/svg';
export function hashSeed(value){let hash=2166136261;for(const character of String(value)){hash^=character.charCodeAt(0);hash=Math.imul(hash,16777619)}return hash>>>0}
export function seededRandom(seed){let state=hashSeed(seed);return()=>{state|=0;state=state+0x6D2B79F5|0;let value=Math.imul(state^state>>>15,1|state);value=value+Math.imul(value^value>>>7,61|value)^value;return((value^value>>>14)>>>0)/4294967296}}
export const pick=(random,values)=>values[Math.floor(random()*values.length)];
export const chance=(random,probability)=>random()<probability;
export const clamp=(value,min,max)=>Math.max(min,Math.min(max,value));
export function roughPath(points,random,{close=false,jitter=1.5}={}){let data=`M ${points[0][0].toFixed(1)} ${points[0][1].toFixed(1)}`;for(let index=1;index<points.length;index++){const point=points[index];data+=` L ${(point[0]+(random()-.5)*jitter).toFixed(1)} ${(point[1]+(random()-.5)*jitter).toFixed(1)}`}return data+(close?' Z':'')}
export function roughLine(from,to,random,options={}){const segments=options.segments??3,points=[];for(let index=0;index<=segments;index++){const amount=index/segments;points.push([from[0]+(to[0]-from[0])*amount,from[1]+(to[1]-from[1])*amount])}return roughPath(points,random,options)}
export function roughEllipse(cx,cy,rx,ry,random,{points=24,noise=.055,jitter=1.5}={}){const shape=[];for(let index=0;index<points;index++){const angle=Math.PI*2*index/points,variation=1+(random()-.5)*noise;shape.push([cx+Math.cos(angle)*rx*variation,cy+Math.sin(angle)*ry*variation])}return roughPath(shape,random,{close:true,jitter})}
export function svgPath(data,attributes='',defaults={fill:'none',stroke:'#25262a'}){const fill=/\bfill=/.test(attributes)?'':`fill="${defaults.fill}" `,stroke=/\bstroke=/.test(attributes)?'':`stroke="${defaults.stroke}" `;return `<path d="${data}" ${fill}${stroke}${attributes}/>`}
export function paperTexture(id='paper-grain'){return `<filter id="${id}" x="-8%" y="-8%" width="116%" height="116%"><feTurbulence type="fractalNoise" baseFrequency=".72" numOctaves="3" seed="17"/><feColorMatrix type="saturate" values="0"/><feComponentTransfer><feFuncA type="table" tableValues="0 .045"/></feComponentTransfer></filter>`}
export function downloadText(name,text,type='image/svg+xml'){const anchor=document.createElement('a');anchor.href=URL.createObjectURL(new Blob([text],{type}));anchor.download=name;anchor.click();setTimeout(()=>URL.revokeObjectURL(anchor.href),500)}
export function downloadSvgAsPng(name,svg,width,height){const image=new Image(),canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;image.onload=()=>{canvas.getContext('2d').drawImage(image,0,0,width,height);canvas.toBlob(blob=>{const anchor=document.createElement('a');anchor.href=URL.createObjectURL(blob);anchor.download=name;anchor.click()},'image/png')};image.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg)}
